pid:
  use_pid: true
  inertia_level: 0.1
wheels:
  distance: 0.24
  circumference: 0.32
speed:
  # Plot x=thunderborg value, y=m/s
  slope: 0.649776
  y_intercept: -0.0788956
  motor_diag_msg: false
